import type { LucideIcon } from "lucide-react";

export const C = {
  bg: "#0B0B0B",
  surface: "#0F0F0F",
  card: "#1F1F1F",
  border: "#2A2A2A",
  white: "#FFFFFF",
  secondary: "#D7D7D7",
  muted: "#9B9B9B",
  gold: "#D4AF37",
  goldBright: "#FFD700",
  burgundy: "#A71930",
  burgundyDark: "#701E20",
  burgundyMid: "#8B3A3A",
  maroon: "#2D1818",
  bronze: "#C4A484",
  goldGrad: "linear-gradient(135deg, #FFD700 0%, #D4AF37 100%)",
  burGrad: "linear-gradient(135deg, #A71930 0%, #C42D40 100%)",
  btnGrad: "linear-gradient(135deg, #A71930 0%, #C42D40 50%, #D45050 100%)",
  btnShadow: "0 4px 0 #781020, 0 6px 24px rgba(167,25,48,0.55), 0 1px 0 rgba(255,255,255,0.12) inset",
  heroGlow1: "radial-gradient(ellipse 75% 65% at 15% 45%, rgba(139,58,58,0.28) 0%, transparent 65%)",
  heroGlow2: "radial-gradient(ellipse 55% 50% at 85% 25%, rgba(212,175,55,0.10) 0%, transparent 60%)",
  sectionGlow: "radial-gradient(ellipse 60% 50% at 50% 50%, rgba(167,25,48,0.06) 0%, transparent 70%)",
} as const;

export type Lang = "EN" | "RU" | "UZ";

export const i18n: Record<Lang, Record<string, string>> = {
  EN: {
    home: "Home", about: "About", courses: "Courses",
    teachers: "Teachers", learning: "Learning Center",
    news: "News", results: "Results", testimonials: "Testimonials",
    videos: "Videos", team: "Team", vacancies: "Vacancies",
    faq: "FAQ", contact: "Contact",
    apply: "Apply Now", apply_position: "Apply for Position",
    experience_label: "Experience / About You",
    experience_placeholder: "Tell us about your experience, skills, and why you are interested in this position...",
    requirements_label: "Requirements",
    application_sent: "Application received!",
    sending_text: "Sending...",
    vacancies_subtitle: "Join a team of passionate legal educators and administrators shaping the future of law in Uzbekistan",
    view_details: "View Details",
    telegram: "Telegram",
    hero_h1: "Become a Future", hero_h2: "Legal Professional",
    hero_sub: "with Tashkent Law School",
    hero_body: "Professional legal education that prepares students for academic excellence and successful careers in law, justice, and governance.",
    learn_more: "Learn More", enroll: "Enroll Now",
    read_more: "Read More", view_profile: "View Profile",
    s_students: "Students", s_admission: "Admission Success",
    s_courses: "Courses", s_teachers: "Professional Teachers",
    s_experience: "Years Experience", s_partners: "Partner Organizations",
    about_label: "Our Story", about_title: "Shaping the Legal Leaders of Tomorrow",
    courses_label: "Education", courses_title: "Our Courses",
    teachers_label: "Faculty", teachers_title: "Expert Educators",
    learning_label: "Campus", learning_title: "Learning Center",
    results_label: "Track Record", results_title: "Our Achievements",
    testimonials_label: "Testimonials", testimonials_title: "Student Stories",
    videos_label: "Video Reviews", videos_title: "Hear From Our Students",
    news_label: "Latest Updates", news_title: "News & Events",
    team_label: "Our Team", team_title: "Leadership",
    vacancies_label: "Join Us", vacancies_title: "Open Positions",
    faq_label: "Support", faq_title: "Frequently Asked Questions",
    contact_label: "Get In Touch", contact_title: "Contact Us",
    firstname: "First Name", lastname: "Last Name",
    phone: "Phone Number", address: "Address",
    course_select: "Preferred Course", submit_enroll: "Submit Application",
    enroll_title: "Apply for Course", enroll_subtitle: "Fill in the form below and we will contact you shortly",
    name: "Name", category: "Category",
    about_mission: "Our Mission",
    about_mission_desc: "To provide world-class legal education that empowers students with the knowledge, skills, and ethical foundation necessary to excel in the legal profession and contribute meaningfully to society.",
    about_vision: "Our Vision",
    about_vision_desc: "To be recognized as the premier law school in Central Asia, producing legal professionals who shape policy, uphold justice, and drive progress across the region and beyond.",
    about_value_integrity: "Integrity",
    about_value_integrity_desc: "Upholding the highest ethical standards in legal education and practice.",
    about_value_excellence: "Excellence",
    about_value_excellence_desc: "Pursuing academic rigor and professional mastery in every program.",
    about_value_community: "Community",
    about_value_community_desc: "Building a supportive network of students, alumni, and legal professionals.",
    about_value_innovation: "Innovation",
    about_value_innovation_desc: "Embracing modern teaching methods and global legal perspectives.",
    about_journey: "Our Journey",
    about_years: "Years of Excellence",
    about_timeline_1_title: "School Founded",
    about_timeline_1_desc: "Tashkent Law School was established with a single classroom and a vision to revolutionize legal education in Uzbekistan.",
    about_timeline_2_title: "First Graduating Class",
    about_timeline_2_desc: "Our inaugural cohort graduated with a 92% employment rate, setting the standard for academic excellence.",
    about_timeline_3_title: "International Accreditation",
    about_timeline_3_desc: "Received accreditation from the Ministry of Justice, expanding our curriculum to meet global legal education standards.",
    about_timeline_4_title: "New Campus Inaugurated",
    about_timeline_4_desc: "Opened a state-of-the-art campus featuring a mock courtroom, digital law library, and modern lecture halls.",
    about_timeline_5_title: "Online Learning Platform",
    about_timeline_5_desc: "Launched a hybrid education model combining in-person sessions with a comprehensive online platform.",
    about_timeline_6_title: "95% Employment Rate",
    about_timeline_6_desc: "Achieved our highest graduate employment rate, with alumni placed at top law firms, courts, and international organizations.",
  },
  RU: {
    home: "Главная", about: "О нас", courses: "Курсы",
    teachers: "Преподаватели", learning: "Учебный центр",
    news: "Новости", results: "Результаты", testimonials: "Отзывы",
    videos: "Видео", team: "Команда", vacancies: "Вакансии",
    faq: "FAQ", contact: "Контакты",
    apply: "Подать заявку", apply_position: "Подать заявку на должность",
    experience_label: "Опыт / О себе",
    experience_placeholder: "Расскажите о своём опыте, навыках и почему вас заинтересовала эта должность...",
    requirements_label: "Требования",
    application_sent: "Заявка принята!",
    sending_text: "Отправка...",
    vacancies_subtitle: "Присоединяйтесь к команде увлечённых преподавателей и администраторов, формирующих будущее права в Узбекистане",
    view_details: "Подробнее",
    telegram: "Telegram",
    hero_h1: "Станьте юристом", hero_h2: "будущего",
    hero_sub: "в Ташкентской школе права",
    hero_body: "Профессиональное юридическое образование, готовящее студентов к академическому совершенству и успешной карьере.",
    learn_more: "Узнать больше", enroll: "Записаться",
    read_more: "Читать далее", view_profile: "Профиль",
    s_students: "Студентов", s_admission: "Успех поступления",
    s_courses: "Курсов", s_teachers: "Преподавателей",
    s_experience: "Лет опыта", s_partners: "Партнёров",
    about_label: "О нас", about_title: "Формируем правовых лидеров завтрашнего дня",
    courses_label: "Образование", courses_title: "Наши курсы",
    teachers_label: "Факультет", teachers_title: "Эксперты-преподаватели",
    learning_label: "Кампус", learning_title: "Учебный центр",
    results_label: "Достижения", results_title: "Наши результаты",
    testimonials_label: "Отзывы", testimonials_title: "Истории студентов",
    videos_label: "Видео отзывы", videos_title: "Слово наших студентов",
    news_label: "Новости", news_title: "Новости и события",
    team_label: "Наша команда", team_title: "Руководство",
    vacancies_label: "Присоединяйтесь", vacancies_title: "Открытые вакансии",
    faq_label: "Поддержка", faq_title: "Часто задаваемые вопросы",
    contact_label: "Связаться", contact_title: "Контакты",
    firstname: "Имя", lastname: "Фамилия",
    phone: "Телефон", address: "Адрес",
    course_select: "Выберите курс", submit_enroll: "Отправить заявку",
    enroll_title: "Записаться на курс", enroll_subtitle: "Заполните форму ниже, и мы свяжемся с вами",
    name: "Имя", category: "Категория",
    about_mission: "Наша миссия",
    about_mission_desc: "Обеспечить юридическое образование мирового уровня, которое даёт студентам знания, навыки и этическую основу, необходимые для успешной карьеры в юриспруденции.",
    about_vision: "Наше видение",
    about_vision_desc: "Быть признанной ведущей школой права в Центральной Азии, выпускающей юристов, формирующих политику, отстаивающих справедливость и стимулирующих прогресс.",
    about_value_integrity: "Честность",
    about_value_integrity_desc: "Соблюдение высочайших этических стандартов в юридическом образовании и практике.",
    about_value_excellence: "Превосходство",
    about_value_excellence_desc: "Стремление к академической строгости и профессиональному мастерству в каждой программе.",
    about_value_community: "Сообщество",
    about_value_community_desc: "Создание поддерживающего сообщества студентов, выпускников и юристов.",
    about_value_innovation: "Инновации",
    about_value_innovation_desc: "Внедрение современных методов обучения и глобальных правовых перспектив.",
    about_journey: "Наш путь",
    about_years: "Лет превосходства",
    about_timeline_1_title: "Основание школы",
    about_timeline_1_desc: "Ташкентская школа права была основана с одним классом и видением революционизировать юридическое образование в Узбекистане.",
    about_timeline_2_title: "Первый выпуск",
    about_timeline_2_desc: "Наш первый выпуск достиг 92% трудоустройства, установив стандарт академического превосходства.",
    about_timeline_3_title: "Международная аккредитация",
    about_timeline_3_desc: "Получена аккредитация Министерства юстиции, расширившая учебную программу до мировых стандартов.",
    about_timeline_4_title: "Новый кампус",
    about_timeline_4_desc: "Открыт современный кампус с учебным залом суда, цифровой библиотекой и современными аудиториями.",
    about_timeline_5_title: "Онлайн-платформа",
    about_timeline_5_desc: "Запущена гибридная модель обучения, сочетающая очные занятия с онлайн-платформой.",
    about_timeline_6_title: "95% трудоустройства",
    about_timeline_6_desc: "Достигнут самый высокий уровень трудоустройства выпускников в ведущих юридических фирмах и судах.",
  },
  UZ: {
    home: "Bosh sahifa", about: "Biz haqimizda", courses: "Kurslar",
    teachers: "O'qituvchilar", learning: "O'quv markazi",
    news: "Yangiliklar", results: "Natijalar", testimonials: "Sharhlar",
    videos: "Video", team: "Jamoa", vacancies: "Vakansiyalar",
    faq: "FAQ", contact: "Aloqa",
    apply: "Ariza topshirish", apply_position: "Lavozimga ariza",
    experience_label: "Tajriba / O'zingiz haqingizda",
    experience_placeholder: "Tajribangiz, ko'nikmalaringiz va ushbu lavozimga nima uchun qiziqayotganingiz haqida yozing...",
    requirements_label: "Talablar",
    application_sent: "Ariza qabul qilindi!",
    sending_text: "Jo'natilmoqda...",
    vacancies_subtitle: "O'zbekistonda huquq kelajagini shakllantirayotgan ehtirosli huquqiy o'qituvchilar va administratorlar jamoasiga qo'shiling",
    view_details: "Batafsil",
    telegram: "Telegram",
    hero_h1: "Kelajakdagi", hero_h2: "huquqshunos bo'ling",
    hero_sub: "Toshkent Huquq Maktabi bilan",
    hero_body: "Talabalarni akademik mukammallik va huquq, adolat va boshqaruvda muvaffaqiyatli kareraga tayyorlaydigan professional huquqiy ta'lim.",
    learn_more: "Ko'proq bilish", enroll: "Ro'yxatdan o'tish",
    read_more: "Ko'proq o'qish", view_profile: "Profilni ko'rish",
    s_students: "Talabalar", s_admission: "Qabul muvaffaqiyati",
    s_courses: "Kurslar", s_teachers: "O'qituvchilar",
    s_experience: "Yillik tajriba", s_partners: "Hamkorlar",
    about_label: "Biz haqimizda", about_title: "Ertangi huquqiy yetakchilarni shakllantirish",
    courses_label: "Kurslar", courses_title: "Bizning kurslar",
    teachers_label: "Fakultet", teachers_title: "Ekspert o'qituvchilar",
    learning_label: "Kampus", learning_title: "O'quv markazi",
    results_label: "Yutuqlar", results_title: "Bizning natijalar",
    testimonials_label: "Sharhlar", testimonials_title: "Talabalar hikoyalari",
    videos_label: "Video sharhlar", videos_title: "Talabalarimiz so'zi",
    news_label: "Yangiliklar", news_title: "Yangiliklar va tadbirlar",
    team_label: "Bizning jamoa", team_title: "Rahbariyat",
    vacancies_label: "Bizga qo'shiling", vacancies_title: "Ochiq lavozimlar",
    faq_label: "Yordam", faq_title: "Ko'p beriladigan savollar",
    contact_label: "Murojaat", contact_title: "Biz bilan bog'laning",
    firstname: "Ism", lastname: "Familiya",
    phone: "Telefon", address: "Manzil",
    course_select: "Kurs tanlash", submit_enroll: "Arizani yuborish",
    enroll_title: "Kursga yozilish", enroll_subtitle: "Quyidagi shaklni to'ldiring va siz bilan bog'lanamiz",
    name: "Ism", category: "Kategoriya",
    about_mission: "Bizning vazifamiz",
    about_mission_desc: "Talabalarni huquqiy kasbda muvaffaqiyatga erishish va jamiyatga hissa qo'shish uchun zarur bilim, ko'nikma va axloqiy asos bilan ta'minlaydigan jahon darajasidagi yuridik ta'lim berish.",
    about_vision: "Bizning maqsadimiz",
    about_vision_desc: "Markaziy Osiyodagi yetakchi huquq maktabi sifatida tan olinib, siyosatni shakllantiruvchi, adolatni himoya qiluvchi va mintaqada taraqqiyotni boshqaruvchi yuridik mutaxassislarni tayyorlash.",
    about_value_integrity: "Halollik",
    about_value_integrity_desc: "Yuridik ta'lim va amaliyotda eng yuqori axloqiy standartlarni qo'llab-quvvatlash.",
    about_value_excellence: "Mukammallik",
    about_value_excellence_desc: "Har bir dasturda akademik qat'iyat va professional mahoratga intilish.",
    about_value_community: "Hamjamiyat",
    about_value_community_desc: "Talabalar, bitiruvchilar va yuridik mutaxassislarning qo'llab-quvvatlovchi tarmog'ini qurish.",
    about_value_innovation: "Innovatsiya",
    about_value_innovation_desc: "Zamonaviy o'qitish usullari va global huquqiy istiqbollarni qabul qilish.",
    about_journey: "Bizning yo'limiz",
    about_years: "Yillik mukammallik",
    about_timeline_1_title: "Maktab tashkil etilgan",
    about_timeline_1_desc: "Toshkent Huquq Maktabi bitta sinf xonasi va O'zbekistonda yuridik ta'limni inqilob qilish vazifasi bilan tashkil etilgan.",
    about_timeline_2_title: "Birinchi bitiruv",
    about_timeline_2_desc: "Birinchi bitiruvchilarimiz 92% ish bilan ta'minlanish darajasiga erishib, akademik mukammallik standartini o'rnatdilar.",
    about_timeline_3_title: "Xalqaro akkreditatsiya",
    about_timeline_3_desc: "Adliya vazirligidan akkreditatsiya olib, o'quv dasturimizni global yuridik ta'lim standartlariga kengaytirdik.",
    about_timeline_4_title: "Yangi kampus ochilgan",
    about_timeline_4_desc: "Sud zali, raqamli kutubxona va zamonaviy o'quv xonalariga ega eng zamonaviy kampus ochildi.",
    about_timeline_5_title: "Onlayn ta'lim platformasi",
    about_timeline_5_desc: "An'anaviy darslarni keng qamrovli onlayn platforma bilan birlashtirgan gibrid ta'lim modeli ishga tushirildi.",
    about_timeline_6_title: "95% ish bilan ta'minlash",
    about_timeline_6_desc: "Bitiruvchilarning eng yuqori ish bilan ta'minlanish darajasiga erishildi, ular yetakchi yuridik firmalar va sudlarda ishga joylashdilar.",
  },
};

export const COURSES = [
  { id: 1, title: "Civil Law Foundation", title_uz: "Fuqarolik huquqi asoslari", title_ru: "Основы гражданского права", desc: "Comprehensive study of civil law principles, contracts, property rights, and legal obligations in the Uzbek legal system.", duration: "6 months", price: "2,400,000 UZS", teacher: "Prof. Alisher Karimov", schedule: "Mon, Wed, Fri — 18:00–20:00", level: "Foundation", img: "photo-1589829545856-d10d557cf95f" },
  { id: 2, title: "Criminal Law & Procedure", title_uz: "Jinoyat huquqi va protsessi", title_ru: "Уголовное право и процесс", desc: "In-depth exploration of criminal law, investigative procedures, courtroom practice, and professional defense strategies.", duration: "8 months", price: "3,200,000 UZS", teacher: "Dr. Malika Yusupova", schedule: "Tue, Thu — 17:00–20:00", level: "Intermediate", img: "photo-1453728013993-6d66e9c9123a" },
  { id: 3, title: "Constitutional Law", title_uz: "Konstitutsiyaviy huquq", title_ru: "Конституционное право", desc: "Study of constitutional principles, human rights, governance structures, and the critical role of the judiciary.", duration: "5 months", price: "2,000,000 UZS", teacher: "Prof. Bobur Toshmatov", schedule: "Sat, Sun — 10:00–14:00", level: "Foundation", img: "photo-1555374018-13a8994ab246" },
  { id: 4, title: "Corporate & Business Law", title_uz: "Korporativ va biznes huquqi", title_ru: "Корпоративное и бизнес-право", desc: "Mergers, acquisitions, corporate governance, commercial contracts, and business dispute resolution mechanisms.", duration: "7 months", price: "3,600,000 UZS", teacher: "Dr. Nilufar Rashidova", schedule: "Mon, Wed — 19:00–21:00", level: "Advanced", img: "photo-1507679799987-c73779587ccf" },
  { id: 5, title: "International Law", title_uz: "Xalqaro huquq", title_ru: "Международное право", desc: "Public and private international law, treaty interpretation, WTO trade law, and international dispute resolution.", duration: "6 months", price: "2,800,000 UZS", teacher: "Prof. Jahongir Mirzayev", schedule: "Fri, Sat — 16:00–19:00", level: "Advanced", img: "photo-1516321318423-f06f85e504b3" },
  { id: 6, title: "Legal English", title_uz: "Huquqiy ingliz tili", title_ru: "Юридический английский", desc: "Master the language of law with advanced legal drafting, contract reading, and courtroom communication skills.", duration: "4 months", price: "1,600,000 UZS", teacher: "Sarah Mitchell, LLM", schedule: "Daily — 08:00–09:30", level: "All Levels", img: "photo-1456513080510-7bf3a84b82f8" },
];

export const TEACHERS = [
  { id: 1, name: "Prof. Alisher Karimov", pos: "Head of Civil Law Department", exp: "18 years", spec: "Civil Law, Contract Law", bio: "Former judge of Tashkent City Court with 18 years of combined practice and academic experience.", img: "photo-1472099645785-5658abf4ff4e" },
  { id: 2, name: "Dr. Malika Yusupova", pos: "Senior Lecturer, Criminal Law", exp: "14 years", spec: "Criminal Law, Criminology", bio: "PhD from MGIMO Moscow. Author of three widely-adopted textbooks on Uzbek criminal procedure.", img: "photo-1494790108377-be9c29b29330" },
  { id: 3, name: "Prof. Bobur Toshmatov", pos: "Constitutional Law Expert", exp: "22 years", spec: "Constitutional Law, Human Rights", bio: "Advisor to the Senate of Uzbekistan and Harvard Kennedy School alumnus.", img: "photo-1560250097-0b93528c311a" },
  { id: 4, name: "Dr. Nilufar Rashidova", pos: "Corporate Law Specialist", exp: "12 years", spec: "Corporate Law, M&A", bio: "Former legal counsel at a Big Four firm. Expert in cross-border transactions.", img: "photo-1573496359142-b8d87734a5a2" },
  { id: 5, name: "Prof. Jahongir Mirzayev", pos: "International Law Head", exp: "20 years", spec: "International Law, WTO", bio: "Represented Uzbekistan in WTO accession negotiations. UNITAR lecturer.", img: "photo-1519085360753-af0119f7cbe7" },
  { id: 6, name: "Sarah Mitchell, LLM", pos: "Legal English Instructor", exp: "10 years", spec: "Legal English, Drafting", bio: "Oxford-trained linguist specializing in legal English for non-native professionals.", img: "photo-1580489944761-15a19d654956" },
];

export const FAQS = [
  { q: "What are the admission requirements?", q_uz: "Qabul shartlari qanday?", q_ru: "Каковы требования для поступления?", a: "To enroll, applicants must hold a secondary school certificate or equivalent. No prior legal knowledge is required for foundation courses.", a_uz: "O'qishga kirish uchun o'rta maktab sertifikati yoki ekvivalenti talab qilinadi. Boshlang'ich kurslar uchun oldindan huquqiy bilim talab qilinmaydi.", a_ru: "Для зачисления необходимо наличие аттестата о среднем образовании или эквивалента. Предварительные юридические знания не требуются." },
  { q: "How much do courses cost?", q_uz: "Kurslar narxi qancha?", q_ru: "Сколько стоят курсы?", a: "Course fees range from 1,600,000 to 3,600,000 UZS depending on the program. Monthly installment payment plans are available.", a_uz: "Kurs narxlari dasturga qarab 1,600,000 dan 3,600,000 UZS gacha. Oylik to'lov rejalari mavjud.", a_ru: "Стоимость курсов варьируется от 1,600,000 до 3,600,000 UZS в зависимости от программы. Доступны планы помесячной оплаты." },
  { q: "Are certificates officially recognized?", q_uz: "Sertifikatlar rasmiy tan olinadimi?", q_ru: "Признаются ли сертификаты официально?", a: "Yes. All certificates are accredited by the Ministry of Justice of Uzbekistan.", a_uz: "Ha. Barcha sertifikatlar O'zbekiston Adliya vazirligi tomonidan akkreditatsiyadan o'tgan.", a_ru: "Да. Все сертификаты аккредитованы Министерством юстиции Узбекистана." },
  { q: "What is the class schedule like?", q_uz: "Dars jadvali qanday?", q_ru: "Каково расписание занятий?", a: "Classes run in morning, afternoon, and evening sessions. Weekend-only schedules are available for most courses.", a_uz: "Darslar ertalab, kunduzi va kechqurun o'tkaziladi. Aksariyat kurslar uchun hafta oxi jadvali mavjud.", a_ru: "Занятия проводятся в утренние, дневные и вечерние смены. Для большинства курсов доступно расписание только по выходным." },
  { q: "Do you offer online education?", q_uz: "Onlayn ta'lim mavjudmi?", q_ru: "Предлагаете ли вы онлайн-обучение?", a: "Yes. We offer a hybrid model combining in-person sessions with a comprehensive online platform.", a_uz: "Ha. Biz shaxsiy darslarni keng qamrovli onlayn platforma bilan birlashtirgan gibrid modelni taklif qilamiz.", a_ru: "Да. Мы предлагаем гибридную модель, сочетающую очные занятия с комплексной онлайн-платформой." },
  { q: "Are scholarships available?", q_uz: "Stipendiyalar mavjudmi?", q_ru: "Доступны ли стипендии?", a: "Yes. Merit-based scholarships cover up to 50% of tuition for students with outstanding academic records.", a_uz: "Ha. Yuqori akademik natijalarga ega talabalar uchun stipendiyalar o'quv to'lovining 50% gacha qoplaydi.", a_ru: "Да. Стипендии за успеваемость покрывают до 50% стоимости обучения для студентов с выдающимися результатами." },
  { q: "What is the faculty's level of experience?", q_uz: "O'qituvchilarning tajriba darajasi qanday?", q_ru: "Какой уровень опыта у преподавателей?", a: "Our faculty consists of practicing attorneys, judges, law professors averaging 15+ years of experience.", a_uz: "Bizning o'qituvchilar tarkibi amaliyotchi advokatlar, sudyalar va o'rtacha 15+ yillik tajribaga ega huquq professorlaridan iborat.", a_ru: "Наш факультет состоит из практикующих адвокатов, судей и профессоров права со средним опытом 15+ лет." },
  { q: "How long are the programs?", q_uz: "Dasturlar qancha davom etadi?", q_ru: "Какова продолжительность программ?", a: "Programs range from 4 months (Legal English) to 8 months (Criminal Law).", a_uz: "Dasturlar 4 oydan (Huquqiy ingliz tili) 8 oygacha (Jinoyat huquqi) davom etadi.", a_ru: "Программы длятся от 4 месяцев (Юридический английский) до 8 месяцев (Уголовное право)." },
];

export const NEWS = [
  { id: 1, title: "Tashkent Law School Signs MoU with Heidelberg University", category: "Announcements", date: "June 28, 2025", author: "Admin", excerpt: "A landmark partnership agreement enables student and faculty exchanges between both prestigious institutions.", img: "photo-1523240795612-9a054b0db644" },
  { id: 2, title: "Our Students Win National Legal Olympiad 2025", category: "Events", date: "June 15, 2025", author: "News Desk", excerpt: "Six of our students swept the top prizes at the national competition, securing gold, silver, and bronze medals.", img: "photo-1501854140801-50d01698950b" },
  { id: 3, title: "New State-of-the-Art Mock Courtroom Opens on Campus", category: "Education", date: "May 30, 2025", author: "Admin", excerpt: "Students can now practice real-world litigation under simulated courtroom conditions.", img: "photo-1531800116490-3fd02ccf50e7" },
  { id: 4, title: "Scholarship Program 2025–26 Applications Now Open", category: "Announcements", date: "May 12, 2025", author: "Admissions", excerpt: "Applications are open for merit and need-based scholarships covering up to 50% of program fees.", img: "photo-1456513080510-7bf3a84b82f8" },
  { id: 5, title: "UN Legal Affairs Expert Delivers Masterclass", category: "Events", date: "April 22, 2025", author: "News Desk", excerpt: "Renowned practitioner Dr. Elena Kovacs delivered a masterclass on international humanitarian law.", img: "photo-1497366216548-37526070297c" },
  { id: 6, title: "95% Graduate Employment Rate Confirmed for 2024", category: "Popular", date: "March 10, 2025", author: "Admin", excerpt: "Our annual employment survey confirms that 95% of 2024 graduates secured legal employment.", img: "photo-1507679799987-c73779587ccf" },
];

export const TEAM = [
  { id: 1, name: "Saidakbar Umarov", role: "Dean", dept: "Executive", img: "photo-1560250097-0b93528c311a" },
  { id: 2, name: "Lola Mirzayeva", role: "Vice Dean, Academic Affairs", dept: "Executive", img: "photo-1573496359142-b8d87734a5a2" },
  { id: 3, name: "Timur Khasanov", role: "Head of Admissions", dept: "Administration", img: "photo-1519085360753-af0119f7cbe7" },
  { id: 4, name: "Gulnara Ergasheva", role: "Marketing Director", dept: "Marketing", img: "photo-1580489944761-15a19d654956" },
  { id: 5, name: "Bekhzod Nazarov", role: "Student Affairs Manager", dept: "Administration", img: "photo-1500648767791-00dcc994a43e" },
  { id: 6, name: "Dilorom Yunusova", role: "Finance Director", dept: "Management", img: "photo-1438761681033-6461ffad8d80" },
  { id: 7, name: "Rustam Tursunov", role: "IT Director", dept: "IT", img: "photo-1472099645785-5658abf4ff4e" },
  { id: 8, name: "Zulfiya Karimova", role: "Communications Manager", dept: "Marketing", img: "photo-1517841905240-472988babdf9" },
];

export const VACANCIES = [
  { id: 1, title: "Senior Law Lecturer — Corporate Law", dept: "Academic", req: "LLM or PhD in Law, 5+ years teaching experience.", salary: "15–25 mln UZS/month", loc: "Tashkent, On-site", type: "Full-time" },
  { id: 2, title: "Student Admissions Officer", dept: "Administration", req: "Higher education, excellent communication, Uzbek/Russian/English.", salary: "8–12 mln UZS/month", loc: "Tashkent, On-site", type: "Full-time" },
  { id: 3, title: "Digital Marketing Specialist", dept: "Marketing", req: "3+ years in digital marketing, SMM, Google and Meta Ads.", salary: "10–18 mln UZS/month", loc: "Tashkent, Hybrid", type: "Full-time" },
  { id: 4, title: "IT Systems Administrator", dept: "IT", req: "Experience with LMS platforms, network administration.", salary: "12–20 mln UZS/month", loc: "Tashkent, On-site", type: "Full-time" },
];
